"""SEC Standard Industrial Classification (SIC) code lookup.

Source: https://www.sec.gov/search-filings/standard-industrial-classification-sic-code-list
444 codes as published by the SEC.

Provides:
    SIC_CODES  — dict mapping sic str → {description, office, division, division_name}
    get_sic_info(sic) — returns the dict for a code, or None if not found
"""

from __future__ import annotations


# fmt: off
SIC_CODES: dict[str, dict] = {
    '100': {
        "description": 'AGRICULTURAL PRODUCTION-CROPS',
        "office": 'Industrial Applications and Services',
        "division": 'A',
        "division_name": 'Agriculture, Forestry, and Fishing',
    },
    '200': {
        "description": 'AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES',
        "office": 'Industrial Applications and Services',
        "division": 'A',
        "division_name": 'Agriculture, Forestry, and Fishing',
    },
    '700': {
        "description": 'AGRICULTURAL SERVICES',
        "office": 'Industrial Applications and Services',
        "division": 'A',
        "division_name": 'Agriculture, Forestry, and Fishing',
    },
    '800': {
        "description": 'FORESTRY',
        "office": 'Industrial Applications and Services',
        "division": 'A',
        "division_name": 'Agriculture, Forestry, and Fishing',
    },
    '900': {
        "description": 'FISHING, HUNTING AND TRAPPING',
        "office": 'Industrial Applications and Services',
        "division": 'A',
        "division_name": 'Agriculture, Forestry, and Fishing',
    },
    '1000': {
        "description": 'METAL MINING',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1040': {
        "description": 'GOLD AND SILVER ORES',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1090': {
        "description": 'MISCELLANEOUS METAL ORES',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1220': {
        "description": 'BITUMINOUS COAL & LIGNITE MINING',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1221': {
        "description": 'BITUMINOUS COAL & LIGNITE SURFACE MINING',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1311': {
        "description": 'CRUDE PETROLEUM & NATURAL GAS',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1381': {
        "description": 'DRILLING OIL & GAS WELLS',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1382': {
        "description": 'OIL & GAS FIELD EXPLORATION SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1389': {
        "description": 'OIL & GAS FIELD SERVICES, NEC',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1400': {
        "description": 'MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)',
        "office": 'Office of Energy & Transportation',
        "division": 'B',
        "division_name": 'Mining',
    },
    '1520': {
        "description": 'GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1531': {
        "description": 'OPERATIVE BUILDERS',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1540': {
        "description": 'GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1600': {
        "description": 'HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1623': {
        "description": 'WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1700': {
        "description": 'CONSTRUCTION - SPECIAL TRADE CONTRACTORS',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '1731': {
        "description": 'ELECTRICAL WORK',
        "office": 'Office of Real Estate & Construction',
        "division": 'C',
        "division_name": 'Construction',
    },
    '2000': {
        "description": 'FOOD AND KINDRED PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2011': {
        "description": 'MEAT PACKING PLANTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2013': {
        "description": 'SAUSAGES & OTHER PREPARED MEAT PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2015': {
        "description": 'POULTRY SLAUGHTERING AND PROCESSING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2020': {
        "description": 'DAIRY PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2024': {
        "description": 'ICE CREAM & FROZEN DESSERTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2030': {
        "description": 'CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2033': {
        "description": 'CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2040': {
        "description": 'GRAIN MILL PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2050': {
        "description": 'BAKERY PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2052': {
        "description": 'COOKIES & CRACKERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2060': {
        "description": 'SUGAR & CONFECTIONERY PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2070': {
        "description": 'FATS & OILS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2080': {
        "description": 'BEVERAGES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2082': {
        "description": 'MALT BEVERAGES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2086': {
        "description": 'BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2090': {
        "description": 'MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2092': {
        "description": 'PREPARED FRESH OR FROZEN FISH & SEAFOODS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2100': {
        "description": 'TOBACCO PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2111': {
        "description": 'CIGARETTES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2200': {
        "description": 'TEXTILE MILL PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2211': {
        "description": 'BROADWOVEN FABRIC MILLS, COTTON',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2221': {
        "description": 'BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2250': {
        "description": 'KNITTING MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2253': {
        "description": 'KNIT OUTERWEAR MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2273': {
        "description": 'CARPETS & RUGS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2300': {
        "description": 'APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2320': {
        "description": "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS",
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2330': {
        "description": "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR",
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2340': {
        "description": "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS",
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2390': {
        "description": 'MISCELLANEOUS FABRICATED TEXTILE PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2400': {
        "description": 'LUMBER & WOOD PRODUCTS (NO FURNITURE)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2421': {
        "description": 'SAWMILLS & PLANTING MILLS, GENERAL',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2430': {
        "description": 'MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2451': {
        "description": 'MOBILE HOMES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2452': {
        "description": 'PREFABRICATED WOOD BLDGS & COMPONENTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2510': {
        "description": 'HOUSEHOLD FURNITURE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2511': {
        "description": 'WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2520': {
        "description": 'OFFICE FURNITURE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2522': {
        "description": 'OFFICE FURNITURE (NO WOOD)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2531': {
        "description": 'PUBLIC BLDG & RELATED FURNITURE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2540': {
        "description": 'PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2590': {
        "description": 'MISCELLANEOUS FURNITURE & FIXTURES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2600': {
        "description": 'PAPERS & ALLIED PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2611': {
        "description": 'PULP MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2621': {
        "description": 'PAPER MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2631': {
        "description": 'PAPERBOARD MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2650': {
        "description": 'PAPERBOARD CONTAINERS & BOXES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2670': {
        "description": 'CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2673': {
        "description": 'PLASTICS, FOIL & COATED PAPER BAGS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2711': {
        "description": 'NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2721': {
        "description": 'PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2731': {
        "description": 'BOOKS: PUBLISHING OR PUBLISHING & PRINTING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2732': {
        "description": 'BOOK PRINTING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2741': {
        "description": 'MISCELLANEOUS PUBLISHING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2750': {
        "description": 'COMMERCIAL PRINTING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2761': {
        "description": 'MANIFOLD BUSINESS FORMS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2771': {
        "description": 'GREETING CARDS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2780': {
        "description": 'BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2790': {
        "description": 'SERVICE INDUSTRIES FOR THE PRINTING TRADE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2800': {
        "description": 'CHEMICALS & ALLIED PRODUCTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2810': {
        "description": 'INDUSTRIAL INORGANIC CHEMICALS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2820': {
        "description": 'PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2821': {
        "description": 'PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2833': {
        "description": 'MEDICINAL CHEMICALS & BOTANICAL PRODUCTS',
        "office": 'Office of Life Sciences',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2834': {
        "description": 'PHARMACEUTICAL PREPARATIONS',
        "office": 'Office of Life Sciences',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2835': {
        "description": 'IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES',
        "office": 'Office of Life Sciences',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2836': {
        "description": 'BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)',
        "office": 'Office of Life Sciences',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2840': {
        "description": 'SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2842': {
        "description": 'SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2844': {
        "description": 'PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2851': {
        "description": 'PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2860': {
        "description": 'INDUSTRIAL ORGANIC CHEMICALS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2870': {
        "description": 'AGRICULTURAL CHEMICALS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2890': {
        "description": 'MISCELLANEOUS CHEMICAL PRODUCTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2891': {
        "description": 'ADHESIVES & SEALANTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2911': {
        "description": 'PETROLEUM REFINING',
        "office": 'Office of Energy & Transportation',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2950': {
        "description": 'ASPHALT PAVING & ROOFING MATERIALS',
        "office": 'Office of Energy & Transportation',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '2990': {
        "description": 'MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL',
        "office": 'Office of Energy & Transportation',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3011': {
        "description": 'TIRES & INNER TUBES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3021': {
        "description": 'RUBBER & PLASTICS FOOTWEAR',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3050': {
        "description": 'GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3060': {
        "description": 'FABRICATED RUBBER PRODUCTS, NEC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3080': {
        "description": 'MISCELLANEOUS PLASTICS PRODUCTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3081': {
        "description": 'UNSUPPORTED PLASTICS FILM & SHEET',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3086': {
        "description": 'PLASTICS FOAM PRODUCTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3089': {
        "description": 'PLASTICS PRODUCTS, NEC',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3100': {
        "description": 'LEATHER & LEATHER PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3140': {
        "description": 'FOOTWEAR, (NO RUBBER)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3211': {
        "description": 'FLAT GLASS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3220': {
        "description": 'GLASS & GLASSWARE, PRESSED OR BLOWN',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3221': {
        "description": 'GLASS CONTAINERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3231': {
        "description": 'GLASS PRODUCTS, MADE OF PURCHASED GLASS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3241': {
        "description": 'CEMENT, HYDRAULIC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3250': {
        "description": 'STRUCTURAL CLAY PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3260': {
        "description": 'POTTERY & RELATED PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3270': {
        "description": 'CONCRETE, GYPSUM & PLASTER PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3272': {
        "description": 'CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3281': {
        "description": 'CUT STONE & STONE PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3290': {
        "description": 'ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3310': {
        "description": 'STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3312': {
        "description": 'STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3317': {
        "description": 'STEEL PIPE & TUBES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3320': {
        "description": 'IRON & STEEL FOUNDRIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3330': {
        "description": 'PRIMARY SMELTING & REFINING OF NONFERROUS METALS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3334': {
        "description": 'PRIMARY PRODUCTION OF ALUMINUM',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3341': {
        "description": 'SECONDARY SMELTING & REFINING OF NONFERROUS METALS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3350': {
        "description": 'ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3357': {
        "description": 'DRAWING & INSULATING OF NONFERROUS WIRE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3360': {
        "description": 'NONFERROUS FOUNDRIES (CASTINGS)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3390': {
        "description": 'MISCELLANEOUS PRIMARY METAL PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3411': {
        "description": 'METAL CANS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3412': {
        "description": 'METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3420': {
        "description": 'CUTLERY, HANDTOOLS & GENERAL HARDWARE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3430': {
        "description": 'HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3433': {
        "description": 'HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3440': {
        "description": 'FABRICATED STRUCTURAL METAL PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3442': {
        "description": 'METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3443': {
        "description": 'FABRICATED PLATE WORK (BOILER SHOPS)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3444': {
        "description": 'SHEET METAL WORK',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3448': {
        "description": 'PREFABRICATED METAL BUILDINGS & COMPONENTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3451': {
        "description": 'SCREW MACHINE PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3452': {
        "description": 'BOLTS, NUTS, SCREWS, RIVETS & WASHERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3460': {
        "description": 'METAL FORGINGS & STAMPINGS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3470': {
        "description": 'COATING, ENGRAVING & ALLIED SERVICES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3480': {
        "description": 'ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3490': {
        "description": 'MISCELLANEOUS FABRICATED METAL PRODUCTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3510': {
        "description": 'ENGINES & TURBINES',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3523': {
        "description": 'FARM MACHINERY & EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3524': {
        "description": 'LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3530': {
        "description": 'CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3531': {
        "description": 'CONSTRUCTION MACHINERY & EQUIP',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3532': {
        "description": 'MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3533': {
        "description": 'OIL & GAS FIELD MACHINERY & EQUIPMENT',
        "office": 'Office of Energy & Transportation',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3537': {
        "description": 'INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3540': {
        "description": 'METALWORKG MACHINERY & EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3541': {
        "description": 'MACHINE TOOLS, METAL CUTTING TYPES',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3550': {
        "description": 'SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3555': {
        "description": 'PRINTING TRADES MACHINERY & EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3559': {
        "description": 'SPECIAL INDUSTRY MACHINERY, NEC',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3560': {
        "description": 'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3561': {
        "description": 'PUMPS & PUMPING EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3562': {
        "description": 'BALL & ROLLER BEARINGS',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3564': {
        "description": 'INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3567': {
        "description": 'INDUSTRIAL PROCESS FURNACES & OVENS',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3569': {
        "description": 'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3570': {
        "description": 'COMPUTER & OFFICE EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3571': {
        "description": 'ELECTRONIC COMPUTERS',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3572': {
        "description": 'COMPUTER STORAGE DEVICES',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3575': {
        "description": 'COMPUTER TERMINALS',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3576': {
        "description": 'COMPUTER COMMUNICATIONS EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3577': {
        "description": 'COMPUTER PERIPHERAL EQUIPMENT, NEC',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3578': {
        "description": 'CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3579': {
        "description": 'OFFICE MACHINES, NEC',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3580': {
        "description": 'REFRIGERATION & SERVICE INDUSTRY MACHINERY',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3585': {
        "description": 'AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3590': {
        "description": 'MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT',
        "office": 'Office of Technology',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3600': {
        "description": 'ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3612': {
        "description": 'POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3613': {
        "description": 'SWITCHGEAR & SWITCHBOARD APPARATUS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3620': {
        "description": 'ELECTRICAL INDUSTRIAL APPARATUS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3621': {
        "description": 'MOTORS & GENERATORS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3630': {
        "description": 'HOUSEHOLD APPLIANCES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3634': {
        "description": 'ELECTRIC HOUSEWARES & FANS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3640': {
        "description": 'ELECTRIC LIGHTING & WIRING EQUIPMENT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3651': {
        "description": 'HOUSEHOLD AUDIO & VIDEO EQUIPMENT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3652': {
        "description": 'PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3661': {
        "description": 'TELEPHONE & TELEGRAPH APPARATUS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3663': {
        "description": 'RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3669': {
        "description": 'COMMUNICATIONS EQUIPMENT, NEC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3670': {
        "description": 'ELECTRONIC COMPONENTS & ACCESSORIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3672': {
        "description": 'PRINTED CIRCUIT BOARDS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3674': {
        "description": 'SEMICONDUCTORS & RELATED DEVICES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3677': {
        "description": 'ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3678': {
        "description": 'ELECTRONIC CONNECTORS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3679': {
        "description": 'ELECTRONIC COMPONENTS, NEC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3690': {
        "description": 'MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3695': {
        "description": 'MAGNETIC & OPTICAL RECORDING MEDIA',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3711': {
        "description": 'MOTOR VEHICLES & PASSENGER CAR BODIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3713': {
        "description": 'TRUCK & BUS BODIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3714': {
        "description": 'MOTOR VEHICLE PARTS & ACCESSORIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3715': {
        "description": 'TRUCK TRAILERS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3716': {
        "description": 'MOTOR HOMES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3720': {
        "description": 'AIRCRAFT & PARTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3721': {
        "description": 'AIRCRAFT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3724': {
        "description": 'AIRCRAFT ENGINES & ENGINE PARTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3728': {
        "description": 'AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3730': {
        "description": 'SHIP & BOAT BUILDING & REPAIRING',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3743': {
        "description": 'RAILROAD EQUIPMENT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3751': {
        "description": 'MOTORCYCLES, BICYCLES & PARTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3760': {
        "description": 'GUIDED MISSILES & SPACE VEHICLES & PARTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3790': {
        "description": 'MISCELLANEOUS TRANSPORTATION EQUIPMENT',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3812': {
        "description": 'SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3821': {
        "description": 'LABORATORY APPARATUS & FURNITURE',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3822': {
        "description": 'AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3823': {
        "description": 'INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3824': {
        "description": 'TOTALIZING FLUID METERS & COUNTING DEVICES',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3825': {
        "description": 'INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3826': {
        "description": 'LABORATORY ANALYTICAL INSTRUMENTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3827': {
        "description": 'OPTICAL INSTRUMENTS & LENSES',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3829': {
        "description": 'MEASURING & CONTROLLING DEVICES, NEC',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3841': {
        "description": 'SURGICAL & MEDICAL INSTRUMENTS & APPARATUS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3842': {
        "description": 'ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3843': {
        "description": 'DENTAL EQUIPMENT & SUPPLIES',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3844': {
        "description": 'X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3845': {
        "description": 'ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3851': {
        "description": 'OPHTHALMIC GOODS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3861': {
        "description": 'PHOTOGRAPHIC EQUIPMENT & SUPPLIES',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3873': {
        "description": 'WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS',
        "office": 'Industrial Applications and Services',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3910': {
        "description": 'JEWELRY, SILVERWARE & PLATED WARE',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3911': {
        "description": 'JEWELRY, PRECIOUS METAL',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3931': {
        "description": 'MUSICAL INSTRUMENTS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3942': {
        "description": 'DOLLS & STUFFED TOYS',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3944': {
        "description": "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)",
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3949': {
        "description": 'SPORTING & ATHLETIC GOODS, NEC',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3950': {
        "description": "PENS, PENCILS & OTHER ARTISTS' MATERIALS",
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3960': {
        "description": 'COSTUME JEWELRY & NOVELTIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '3990': {
        "description": 'MISCELLANEOUS MANUFACTURING INDUSTRIES',
        "office": 'Office of Manufacturing',
        "division": 'D',
        "division_name": 'Manufacturing',
    },
    '4011': {
        "description": 'RAILROADS, LINE-HAUL OPERATING',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4013': {
        "description": 'RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4100': {
        "description": 'LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4210': {
        "description": 'TRUCKING & COURIER SERVICES (NO AIR)',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4213': {
        "description": 'TRUCKING (NO LOCAL)',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4220': {
        "description": 'PUBLIC WAREHOUSING & STORAGE',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4231': {
        "description": 'TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4400': {
        "description": 'WATER TRANSPORTATION',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4412': {
        "description": 'DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4512': {
        "description": 'AIR TRANSPORTATION, SCHEDULED',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4513': {
        "description": 'AIR COURIER SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4522': {
        "description": 'AIR TRANSPORTATION, NONSCHEDULED',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4581': {
        "description": 'AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4610': {
        "description": 'PIPE LINES (NO NATURAL GAS)',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4700': {
        "description": 'TRANSPORTATION SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4731': {
        "description": 'ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4812': {
        "description": 'RADIOTELEPHONE COMMUNICATIONS',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4813': {
        "description": 'TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4822': {
        "description": 'TELEGRAPH & OTHER MESSAGE COMMUNICATIONS',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4832': {
        "description": 'RADIO BROADCASTING STATIONS',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4833': {
        "description": 'TELEVISION BROADCASTING STATIONS',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4841': {
        "description": 'CABLE & OTHER PAY TELEVISION SERVICES',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4899': {
        "description": 'COMMUNICATIONS SERVICES, NEC',
        "office": 'Office of Technology',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4900': {
        "description": 'ELECTRIC, GAS & SANITARY SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4911': {
        "description": 'ELECTRIC SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4922': {
        "description": 'NATURAL GAS TRANSMISSION',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4923': {
        "description": 'NATURAL GAS TRANSMISISON & DISTRIBUTION',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4924': {
        "description": 'NATURAL GAS DISTRIBUTION',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4931': {
        "description": 'ELECTRIC & OTHER SERVICES COMBINED',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4932': {
        "description": 'GAS & OTHER SERVICES COMBINED',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4941': {
        "description": 'WATER SUPPLY',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4950': {
        "description": 'SANITARY SERVICES',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4953': {
        "description": 'REFUSE SYSTEMS',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4955': {
        "description": 'HAZARDOUS WASTE MANAGEMENT',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4961': {
        "description": 'STEAM & AIR-CONDITIONING SUPPLY',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '4991': {
        "description": 'COGENERATION SERVICES & SMALL POWER PRODUCERS',
        "office": 'Office of Energy & Transportation',
        "division": 'E',
        "division_name": 'Transportation, Communications, Electric, Gas, and Sanitary Services',
    },
    '5000': {
        "description": 'WHOLESALE-DURABLE GOODS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5010': {
        "description": 'WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5013': {
        "description": 'WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5020': {
        "description": 'WHOLESALE-FURNITURE & HOME FURNISHINGS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5030': {
        "description": 'WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5031': {
        "description": 'WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5040': {
        "description": 'WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5045': {
        "description": 'WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5047': {
        "description": 'WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5050': {
        "description": 'WHOLESALE-METALS & MINERALS (NO PETROLEUM)',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5051': {
        "description": 'WHOLESALE-METALS SERVICE CENTERS & OFFICES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5063': {
        "description": 'WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5064': {
        "description": 'WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5065': {
        "description": 'WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5070': {
        "description": 'WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5072': {
        "description": 'WHOLESALE-HARDWARE',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5080': {
        "description": 'WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5082': {
        "description": 'WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5084': {
        "description": 'WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5090': {
        "description": 'WHOLESALE-MISC DURABLE GOODS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5094': {
        "description": 'WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5099': {
        "description": 'WHOLESALE-DURABLE GOODS, NEC',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5110': {
        "description": 'WHOLESALE-PAPER & PAPER PRODUCTS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5122': {
        "description": "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES",
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5130': {
        "description": 'WHOLESALE-APPAREL, PIECE GOODS & NOTIONS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5140': {
        "description": 'WHOLESALE-GROCERIES & RELATED PRODUCTS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5141': {
        "description": 'WHOLESALE-GROCERIES, GENERAL LINE',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5150': {
        "description": 'WHOLESALE-FARM PRODUCT RAW MATERIALS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5160': {
        "description": 'WHOLESALE-CHEMICALS & ALLIED PRODUCTS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5171': {
        "description": 'WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5172': {
        "description": 'WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5180': {
        "description": 'WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5190': {
        "description": 'WHOLESALE-MISCELLANEOUS NONDURABLE GOODS',
        "office": 'Office of Trade & Services',
        "division": 'F',
        "division_name": 'Wholesale Trade',
    },
    '5200': {
        "description": 'RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5211': {
        "description": 'RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5271': {
        "description": 'RETAIL-MOBILE HOME DEALERS',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5311': {
        "description": 'RETAIL-DEPARTMENT STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5331': {
        "description": 'RETAIL-VARIETY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5399': {
        "description": 'RETAIL-MISC GENERAL MERCHANDISE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5400': {
        "description": 'RETAIL-FOOD STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5411': {
        "description": 'RETAIL-GROCERY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5412': {
        "description": 'RETAIL-CONVENIENCE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5500': {
        "description": 'RETAIL-AUTO DEALERS & GASOLINE STATIONS',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5531': {
        "description": 'RETAIL-AUTO & HOME SUPPLY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5600': {
        "description": 'RETAIL-APPAREL & ACCESSORY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5621': {
        "description": "RETAIL-WOMEN'S CLOTHING STORES",
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5651': {
        "description": 'RETAIL-FAMILY CLOTHING STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5661': {
        "description": 'RETAIL-SHOE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5700': {
        "description": 'RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5712': {
        "description": 'RETAIL-FURNITURE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5731': {
        "description": 'RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5734': {
        "description": 'RETAIL-COMPUTER & COMPUTER SOFTWARE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5735': {
        "description": 'RETAIL-RECORD & PRERECORDED TAPE STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5810': {
        "description": 'RETAIL-EATING & DRINKING PLACES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5812': {
        "description": 'RETAIL-EATING PLACES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5900': {
        "description": 'RETAIL-MISCELLANEOUS RETAIL',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5912': {
        "description": 'RETAIL-DRUG STORES AND PROPRIETARY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5940': {
        "description": 'RETAIL-MISCELLANEOUS SHOPPING GOODS STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5944': {
        "description": 'RETAIL-JEWELRY STORES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5945': {
        "description": 'RETAIL-HOBBY, TOY & GAME SHOPS',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5960': {
        "description": 'RETAIL-NONSTORE RETAILERS',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5961': {
        "description": 'RETAIL-CATALOG & MAIL-ORDER HOUSES',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '5990': {
        "description": 'RETAIL-RETAIL STORES, NEC',
        "office": 'Office of Trade & Services',
        "division": 'G',
        "division_name": 'Retail Trade',
    },
    '6021': {
        "description": 'NATIONAL COMMERCIAL BANKS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6022': {
        "description": 'STATE COMMERCIAL BANKS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6029': {
        "description": 'COMMERCIAL BANKS, NEC',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6035': {
        "description": 'SAVINGS INSTITUTION, FEDERALLY CHARTERED',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6036': {
        "description": 'SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6099': {
        "description": 'FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6111': {
        "description": 'FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6141': {
        "description": 'PERSONAL CREDIT INSTITUTIONS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6153': {
        "description": 'SHORT-TERM BUSINESS CREDIT INSTITUTIONS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6159': {
        "description": 'MISCELLANEOUS BUSINESS CREDIT INSTITUTION',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6162': {
        "description": 'MORTGAGE BANKERS & LOAN CORRESPONDENTS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6163': {
        "description": 'LOAN BROKERS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6172': {
        "description": 'FINANCE LESSORS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6189': {
        "description": 'ASSET-BACKED SECURITIES',
        "office": 'Office of Structured Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6199': {
        "description": 'FINANCE SERVICES',
        "office": 'Office of Finance or Office of Crypto Assets',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6200': {
        "description": 'SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES',
        "office": 'Office of Crypto Assets',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6211': {
        "description": 'SECURITY BROKERS, DEALERS & FLOTATION COMPANIES',
        "office": 'Office of Finance or Office of Crypto Assets',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6221': {
        "description": 'COMMODITY CONTRACTS BROKERS & DEALERS',
        "office": 'Office of Crypto Assets',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6282': {
        "description": 'INVESTMENT ADVICE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6311': {
        "description": 'LIFE INSURANCE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6321': {
        "description": 'ACCIDENT & HEALTH INSURANCE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6324': {
        "description": 'HOSPITAL & MEDICAL SERVICE PLANS',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6331': {
        "description": 'FIRE, MARINE & CASUALTY INSURANCE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6351': {
        "description": 'SURETY INSURANCE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6361': {
        "description": 'TITLE INSURANCE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6399': {
        "description": 'INSURANCE CARRIERS, NEC',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6411': {
        "description": 'INSURANCE AGENTS, BROKERS & SERVICE',
        "office": 'Office of Finance',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6500': {
        "description": 'REAL ESTATE',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6510': {
        "description": 'REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6512': {
        "description": 'OPERATORS OF NONRESIDENTIAL BUILDINGS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6513': {
        "description": 'OPERATORS OF APARTMENT BUILDINGS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6519': {
        "description": 'LESSORS OF REAL PROPERTY, NEC',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6531': {
        "description": 'REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6532': {
        "description": 'REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6552': {
        "description": 'LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6770': {
        "description": 'BLANK CHECKS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6792': {
        "description": 'OIL ROYALTY TRADERS',
        "office": 'Office of Energy & Transportation',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6794': {
        "description": 'PATENT OWNERS & LESSORS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6795': {
        "description": 'MINERAL ROYALTY TRADERS',
        "office": 'Office of Energy & Transportation',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6798': {
        "description": 'REAL ESTATE INVESTMENT TRUSTS',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '6799': {
        "description": 'INVESTORS, NEC',
        "office": 'Office of Real Estate & Construction',
        "division": 'H',
        "division_name": 'Finance, Insurance, and Real Estate',
    },
    '7000': {
        "description": 'HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES',
        "office": 'Office of Real Estate & Construction',
        "division": 'I',
        "division_name": 'Services',
    },
    '7011': {
        "description": 'HOTELS & MOTELS',
        "office": 'Office of Real Estate & Construction',
        "division": 'I',
        "division_name": 'Services',
    },
    '7200': {
        "description": 'SERVICES-PERSONAL SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7310': {
        "description": 'SERVICES-ADVERTISING',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7311': {
        "description": 'SERVICES-ADVERTISING AGENCIES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7320': {
        "description": 'SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7330': {
        "description": 'SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7331': {
        "description": 'SERVICES-DIRECT MAIL ADVERTISING SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7340': {
        "description": 'SERVICES-TO DWELLINGS & OTHER BUILDINGS',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7350': {
        "description": 'SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7359': {
        "description": 'SERVICES-EQUIPMENT RENTAL & LEASING, NEC',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7361': {
        "description": 'SERVICES-EMPLOYMENT AGENCIES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7363': {
        "description": 'SERVICES-HELP SUPPLY SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7370': {
        "description": 'SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.',
        "office": 'Office of Technology',
        "division": 'I',
        "division_name": 'Services',
    },
    '7371': {
        "description": 'SERVICES-COMPUTER PROGRAMMING SERVICES',
        "office": 'Office of Technology',
        "division": 'I',
        "division_name": 'Services',
    },
    '7372': {
        "description": 'SERVICES-PREPACKAGED SOFTWARE',
        "office": 'Office of Technology',
        "division": 'I',
        "division_name": 'Services',
    },
    '7373': {
        "description": 'SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN',
        "office": 'Office of Technology',
        "division": 'I',
        "division_name": 'Services',
    },
    '7374': {
        "description": 'SERVICES-COMPUTER PROCESSING & DATA PREPARATION',
        "office": 'Office of Technology',
        "division": 'I',
        "division_name": 'Services',
    },
    '7377': {
        "description": 'SERVICES-COMPUTER RENTAL & LEASING',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7380': {
        "description": 'SERVICES-MISCELLANEOUS BUSINESS SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7381': {
        "description": 'SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7384': {
        "description": 'SERVICES-PHOTOFINISHING LABORATORIES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7385': {
        "description": 'SERVICES-TELEPHONE INTERCONNECT SYSTEMS',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7389': {
        "description": 'SERVICES-BUSINESS SERVICES, NEC',
        "office": 'Office of Trade & Services or Office of Energy & Transportation',
        "division": 'I',
        "division_name": 'Services',
    },
    '7500': {
        "description": 'SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7510': {
        "description": 'SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7600': {
        "description": 'SERVICES-MISCELLANEOUS REPAIR SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7812': {
        "description": 'SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7819': {
        "description": 'SERVICES-ALLIED TO MOTION PICTURE PRODUCTION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7822': {
        "description": 'SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7829': {
        "description": 'SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7830': {
        "description": 'SERVICES-MOTION PICTURE THEATERS',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7841': {
        "description": 'SERVICES-VIDEO TAPE RENTAL',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7900': {
        "description": 'SERVICES-AMUSEMENT & RECREATION SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7948': {
        "description": 'SERVICES-RACING, INCLUDING TRACK OPERATION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7990': {
        "description": 'SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '7997': {
        "description": 'SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8000': {
        "description": 'SERVICES-HEALTH SERVICES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8011': {
        "description": 'SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8050': {
        "description": 'SERVICES-NURSING & PERSONAL CARE FACILITIES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8051': {
        "description": 'SERVICES-SKILLED NURSING CARE FACILITIES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8060': {
        "description": 'SERVICES-HOSPITALS',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8062': {
        "description": 'SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8071': {
        "description": 'SERVICES-MEDICAL LABORATORIES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8082': {
        "description": 'SERVICES-HOME HEALTH CARE SERVICES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8090': {
        "description": 'SERVICES-MISC HEALTH & ALLIED SERVICES, NEC',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8093': {
        "description": 'SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8111': {
        "description": 'SERVICES-LEGAL SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8200': {
        "description": 'SERVICES-EDUCATIONAL SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8300': {
        "description": 'SERVICES-SOCIAL SERVICES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8351': {
        "description": 'SERVICES-CHILD DAY CARE SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8600': {
        "description": 'SERVICES-MEMBERSHIP ORGANIZATIONS',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8700': {
        "description": 'SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8711': {
        "description": 'SERVICES-ENGINEERING SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8731': {
        "description": 'SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8734': {
        "description": 'SERVICES-TESTING LABORATORIES',
        "office": 'Industrial Applications and Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8741': {
        "description": 'SERVICES-MANAGEMENT SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8742': {
        "description": 'SERVICES-MANAGEMENT CONSULTING SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8744': {
        "description": 'SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '8880': {
        "description": 'AMERICAN DEPOSITARY RECEIPTS',
        "office": 'Office of International Corp Fin',
        "division": 'I',
        "division_name": 'Services',
    },
    '8888': {
        "description": 'FOREIGN GOVERNMENTS',
        "office": 'Office of International Corp Fin',
        "division": 'I',
        "division_name": 'Services',
    },
    '8900': {
        "description": 'SERVICES-SERVICES, NEC',
        "office": 'Office of Trade & Services',
        "division": 'I',
        "division_name": 'Services',
    },
    '9721': {
        "description": 'INTERNATIONAL AFFAIRS',
        "office": 'Office of International Corp Fin',
        "division": 'J',
        "division_name": 'Public Administration',
    },
    '9995': {
        "description": 'NON-OPERATING ESTABLISHMENTS',
        "office": 'Office of Real Estate & Construction',
        "division": 'J',
        "division_name": 'Public Administration',
    },
}
# fmt: on


def get_sic_info(sic: str | None) -> dict | None:
    """Return {description, office, division, division_name} for a SIC code, or None."""
    if sic is None:
        return None
    return SIC_CODES.get(str(sic).lstrip("0") or "0")
